import React from 'react';
import { Link } from 'react-router-dom';

export const RealEstateSEO = () => {
  return (
    <article className="mt-20 space-y-20 text-slate-700 leading-relaxed border-t border-slate-200 pt-20 max-w-5xl mx-auto px-4 font-sans text-justify">
      {/* Header Section */}
      <header className="text-center space-y-8">
        <div className="inline-flex items-center gap-2 px-6 py-2 bg-slate-100 text-slate-700 rounded-full text-xs font-black uppercase tracking-widest border border-slate-200">
          Property Investment & Capital Gains
        </div>
        <h2 className="text-4xl md:text-6xl font-black text-slate-900 leading-tight">
          Real Estate ROI Calculator Pakistan: <br />
          <span className="text-emerald-600 italic">Calculate True Yield & Profits</span>
        </h2>
        <p className="text-xl text-slate-500 max-w-4xl mx-auto leading-relaxed text-center">
          Investing in property (files, plots, or houses) in DHA, Bahria Town, or CDA sectors is a staple of wealth building in Pakistan. However, hidden costs like CVT, Stamp Duty, and agent commissions often eat into your profits. Our <strong>Real Estate ROI Calculator Pakistan</strong> helps you calculate your true Return on Investment (ROI), Capital Gains, and Rental Yield after accounting for all transactional costs.
        </p>
      </header>

      {/* Section: Understanding Costs */}
      <section className="space-y-12">
        <h2 className="text-3xl font-bold text-slate-900 border-l-8 border-emerald-500 pl-6">The Hidden Costs of Property Investment</h2>
        <p className="text-slate-600 leading-relaxed">
          When you buy a property for PKR 1 Crore and sell it for PKR 1.5 Crore a few years later, your profit isn't simply 50 Lacs. To calculate the actual ROI, you must subtract the frictional costs of trading real estate in Pakistan.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-slate-50 border border-slate-200 p-8 rounded-[2rem]">
            <h3 className="text-xl font-bold text-slate-900 mb-4">Acquisition Costs (Buying)</h3>
            <ul className="list-disc pl-5 space-y-3 text-sm text-slate-700 marker:text-emerald-500">
              <li><strong>Stamp Duty:</strong> Varies by province (e.g., 1-2% in Punjab/Sindh).</li>
              <li><strong>CVT & TMA Tax:</strong> Capital Value Tax and town taxes.</li>
              <li><strong>FBR Advance Tax:</strong> 3% for Filers, much higher for Non-Filers (Sec 236K).</li>
              <li><strong>Agent Commission:</strong> Typically 1% to 2% of the total deal value.</li>
            </ul>
          </div>
          
          <div className="bg-white border border-slate-200 p-8 rounded-[2rem] shadow-sm">
            <h3 className="text-xl font-bold text-slate-900 mb-4">Disposition Costs (Selling)</h3>
            <ul className="list-disc pl-5 space-y-3 text-sm text-slate-700 marker:text-emerald-500">
              <li><strong>Capital Gains Tax (CGT):</strong> FBR taxes profits depending on holding period (0% to 15% under Sec 37).</li>
              <li><strong>FBR Advance Tax on Sale:</strong> 3% for Filers (Sec 236C).</li>
              <li><strong>Agent Commission:</strong> Another 1% to 2% paid to the estate agent when selling.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Section: Yield vs Capital Gains */}
      <section className="bg-emerald-50 border border-emerald-100 p-10 rounded-[3rem]">
        <h2 className="text-3xl font-bold text-emerald-900 text-center mb-6">Rental Yield vs. Capital Gains</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          <div>
            <h4 className="font-bold text-emerald-800 text-lg mb-2">Rental Yield (ROI)</h4>
            <p className="text-sm text-emerald-700">
              This measures the annual cash flow generated by the property. In Pakistan, residential rental yields hover around <strong>3% to 5%</strong>, while commercial properties can offer <strong>6% to 8%</strong>.
              <br/><br/><em>Formula: (Annual Rent / Property Value) × 100</em>
            </p>
          </div>
          <div>
            <h4 className="font-bold text-emerald-800 text-lg mb-2">Capital Appreciation (CAGR)</h4>
            <p className="text-sm text-emerald-700">
              This is the increase in the property's market value over time. While rental yields in Pakistan are low globally, investors historically rely on high Capital Appreciation (e.g., buying a plot and holding it for 5 years).
            </p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="space-y-8 pt-10 border-t border-slate-200">
        <h2 className="text-3xl font-bold text-slate-900 text-center">Frequently Asked Questions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[
            {
              q: "What is FBR Capital Gains Tax (CGT) on property?",
              a: "Under the Finance Act, profit made from selling real estate is taxed. The rate depends on the type of property (Open Plot, Constructed, Flats) and the holding period. Generally, if you hold the property longer (e.g., over 3-6 years), the tax rate drops to zero."
            },
            {
              q: "Should I buy files or constructed property?",
              a: "Files (un-balloted plots) offer high capital gains but zero rental yield and high risk. Constructed properties offer immediate rental yield (cash flow) but slower capital appreciation."
            },
            {
              q: "What is the standard property agent commission in Pakistan?",
              a: "The market standard is 1% to 2% from both the buyer and the seller. However, this is negotiable depending on the deal size and the specific real estate agency."
            },
            {
              q: "Do Non-Filers pay more property taxes?",
              a: "Yes. Non-filers pay substantially higher Advance Taxes (Sec 236C and 236K) when buying or selling property compared to Active Taxpayers (Filers), making it highly unprofitable to invest without being a Filer."
            }
          ].map((faq, i) => (
            <div key={i} className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
              <h4 className="font-bold text-slate-900 mb-2">{faq.q}</h4>
              <p className="text-sm text-slate-600">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Internal Linking */}
      <section className="bg-slate-50 p-8 rounded-3xl text-center">
        <h3 className="font-bold text-slate-900 mb-4">Complete Your Investment Analysis</h3>
        <p className="text-sm text-slate-600 mb-6">Evaluating a real estate deal? You might also need these tools.</p>
        <div className="flex justify-center gap-4 flex-wrap">
          <Link to="/loan-emi" className="px-6 py-2 bg-emerald-600 text-white rounded-full font-bold shadow-sm hover:shadow-md transition-shadow">Calculate Home Loan EMI</Link>
          <Link to="/income-tax" className="px-6 py-2 bg-white border border-slate-200 rounded-full text-slate-700 font-bold shadow-sm hover:shadow-md transition-shadow">Filer Tax Calculator</Link>
        </div>
      </section>

      {/* Footer Meta */}
      <footer className="pt-20 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="text-[10px] text-slate-400 uppercase font-black tracking-widest">
          Updated: Sept 2026 | Real Estate Taxation & Yields
        </div>
        <div className="flex gap-4 flex-wrap">
          <span className="px-3 py-1 bg-slate-100 rounded-full text-[10px] font-bold text-slate-600 italic">real estate roi calculator</span>
          <span className="px-3 py-1 bg-slate-100 rounded-full text-[10px] font-bold text-slate-600 italic">property tax fbr</span>
        </div>
      </footer>
    </article>
  );
};
